-- ---------------------------------------------------------------------------
--  Content fixes after the 2026-09-09 site review (supabase/content_fixes.sql)
--
--  1. Wiktionary imports whose romanization was cut short. Wiktionary writes
--     a syllable's context pronunciation as "cit>actual" inside the word
--     (仂囝 nék>ník-giāng); the harvest split the whole word at ">" and kept
--     only what came before it. Rebuilt here from the two halves, and the
--     "Pronounced …" note gets the markers (* ! \) stripped as well.
--  2. "short for for" → "short for"; 矮嫩 "short for and small" → "short and small".
--  3. Senses labelled for another Chinese variety (Sichuan, Putian, Danyang…)
--     are removed — the character has a Fuzhou reading but that meaning is
--     not attested for Fuzhou. A word left with no meaning goes back to
--     pending with a review note.
--  Every statement is keyed by hanzi + the exact old text, so re-running is
--  a no-op. Generated by scripts/content-fixes.py.
-- ---------------------------------------------------------------------------
begin;

-- 1. romanization rebuilt (78 words)
update public.entries set romanization = 'siŏh-dék-giāng', headword = case when headword = 'siŏh-dék' then 'siŏh-dék-giāng' else headword end where hanzi = '一滴囝' and romanization = 'siŏh-dék';
update public.entries set notes = replace(notes, 'Pronounced dík-giāng.', 'Pronounced siŏh-dík-giāng.') where hanzi = '一滴囝' and notes like '%Pronounced dík-giāng.%';
update public.entries set romanization = 'liáng-siáng', headword = case when headword = 'liáng' then 'liáng-siáng' else headword end where hanzi = '亮線' and romanization = 'liáng';
update public.entries set romanization = 'nék-giāng', headword = case when headword = 'nék' then 'nék-giāng' else headword end where hanzi = '仂囝' and romanization = 'nék';
update public.entries set romanization = 'lék-dék', headword = case when headword = 'lék' then 'lék-dék' else headword end where hanzi = '仂滴' and romanization = 'lék';
update public.entries set romanization = 'ĭ gáuk-nè̤ng', headword = case when headword = 'ĭ gáuk' then 'ĭ gáuk-nè̤ng' else headword end where hanzi = '伊各儂' and romanization = 'ĭ gáuk';
update public.entries set notes = replace(notes, 'Pronounced gó̤k-nè̤ng.', 'Pronounced ĭ gó̤k-nè̤ng.') where hanzi = '伊各儂' and notes like '%Pronounced gó̤k-nè̤ng.%';
update public.entries set romanization = 'nē̤ng-gă-gáuk-nè̤ng', headword = case when headword = 'nē̤ng-gă-gáuk' then 'nē̤ng-gă-gáuk-nè̤ng' else headword end where hanzi = '儂家各儂' and romanization = 'nē̤ng-gă-gáuk';
update public.entries set notes = replace(notes, 'Pronounced gó̤k-nè̤ng.', 'Pronounced nē̤ng-gă-gó̤k-nè̤ng.') where hanzi = '儂家各儂' and notes like '%Pronounced gó̤k-nè̤ng.%';
update public.entries set romanization = 'lâng-gá-siăng', headword = case when headword = 'lâng-gá' then 'lâng-gá-siăng' else headword end where hanzi = '兩個聲' and romanization = 'lâng-gá';
update public.entries set notes = replace(notes, 'Pronounced gā-siăng.', 'Pronounced lâng-gā-siăng.') where hanzi = '兩個聲' and notes like '%Pronounced gā-siăng.%';
update public.entries set romanization = 'báik-nguŏk-sĕk-ngô', headword = case when headword = 'báik-nguŏk-sĕk' then 'báik-nguŏk-sĕk-ngô' else headword end where hanzi = '八月十五' and romanization = 'báik-nguŏk-sĕk';
update public.entries set notes = replace(notes, 'Pronounced sĕh-ngô.', 'Pronounced báik-nguŏk-sĕh-ngô.') where hanzi = '八月十五' and notes like '%Pronounced sĕh-ngô.%';
update public.entries set romanization = 'tié-tàu-să-hô', headword = case when headword = 'tié' then 'tié-tàu-să-hô' else headword end where hanzi = '剃頭師傅' and romanization = 'tié';
update public.entries set romanization = 'sĕk-ciŏk-gŏ̤', headword = case when headword = 'sĕk-ciŏk' then 'sĕk-ciŏk-gŏ̤' else headword end where hanzi = '十絕哥' and romanization = 'sĕk-ciŏk';
update public.entries set notes = replace(notes, 'Pronounced cióh-*gŏ̤.', 'Pronounced sĕk-cióh-gŏ̤.') where hanzi = '十絕哥' and notes like '%Pronounced cióh-*gŏ̤.%';
update public.entries set romanization = 'hióng-nĭh-gì', headword = case when headword = 'hióng-nĭh' then 'hióng-nĭh-gì' else headword end where hanzi = '向日葵' and romanization = 'hióng-nĭh';
update public.entries set notes = replace(notes, 'Pronounced nĭ-*gì.', 'Pronounced hióng-nĭ-gì.') where hanzi = '向日葵' and notes like '%Pronounced nĭ-*gì.%';
update public.entries set romanization = 'gáuk-nè̤ng', headword = case when headword = 'gáuk' then 'gáuk-nè̤ng' else headword end where hanzi = '各儂' and romanization = 'gáuk';
update public.entries set romanization = 'gáuk-nè̤ng', headword = case when headword = 'gáuk' then 'gáuk-nè̤ng' else headword end where hanzi = '各人' and romanization = 'gáuk';
update public.entries set romanization = 'ngiê-sĕng-sŏng-sái', headword = case when headword = 'ngiê' then 'ngiê-sĕng-sŏng-sái' else headword end where hanzi = '外甥孫婿' and romanization = 'ngiê';
update public.entries set romanization = 'tiĕng-gēu siăh-nĭk', headword = case when headword = 'tiĕng-gēu siăh' then 'tiĕng-gēu siăh-nĭk' else headword end where hanzi = '天狗食日' and romanization = 'tiĕng-gēu siăh';
update public.entries set notes = replace(notes, 'Pronounced siék-nĭk.', 'Pronounced tiĕng-gēu siék-nĭk.') where hanzi = '天狗食日' and notes like '%Pronounced siék-nĭk.%';
update public.entries set romanization = 'tiĕng-gēu siăh-nguŏk', headword = case when headword = 'tiĕng-gēu siăh' then 'tiĕng-gēu siăh-nguŏk' else headword end where hanzi = '天狗食月' and romanization = 'tiĕng-gēu siăh';
update public.entries set notes = replace(notes, 'Pronounced siék-nguŏk.', 'Pronounced tiĕng-gēu siék-nguŏk.') where hanzi = '天狗食月' and notes like '%Pronounced siék-nguŏk.%';
update public.entries set romanization = 'mū-mū', headword = case when headword = 'mū' then 'mū-mū' else headword end where hanzi = '姆姆' and romanization = 'mū';
update public.entries set romanization = 'hài-ì', headword = case when headword = 'hài' then 'hài-ì' else headword end where hanzi = '孩兒' and romanization = 'hài';
update public.entries set romanization = 'siŏh-ciéng', headword = case when headword = 'siŏh' then 'siŏh-ciéng' else headword end where hanzi = '射箭' and romanization = 'siŏh';
update public.entries set notes = replace(notes, 'Pronounced sióh-*ciéng.', 'Pronounced sióh-ciéng.') where hanzi = '射箭' and notes like '%Pronounced sióh-*ciéng.%';
update public.entries set romanization = 'uōng-nièng-màng', headword = case when headword = 'uōng-nièng' then 'uōng-nièng-màng' else headword end where hanzi = '往年暝' and romanization = 'uōng-nièng';
update public.entries set notes = replace(notes, 'Pronounced niĕng-màng.', 'Pronounced uōng-niĕng-màng.') where hanzi = '往年暝' and notes like '%Pronounced niĕng-màng.%';
update public.entries set romanization = 'âu-dāu', headword = case when headword = 'âu' then 'âu-dāu' else headword end where hanzi = '後斗' and romanization = 'âu';
update public.entries set romanization = 'âu-dāu-biĕng', headword = case when headword = 'âu' then 'âu-dāu-biĕng' else headword end where hanzi = '後斗邊' and romanization = 'âu';
update public.entries set romanization = 'âu-dāu-sié', headword = case when headword = 'âu' then 'âu-dāu-sié' else headword end where hanzi = '後斗勢' and romanization = 'âu';
update public.entries set romanization = 'kuái-sṳ̆k-miêng', headword = case when headword = 'kuái-sṳ̆k' then 'kuái-sṳ̆k-miêng' else headword end where hanzi = '快熟麵' and romanization = 'kuái-sṳ̆k';
update public.entries set notes = replace(notes, 'Pronounced sṳ́k-miêng.', 'Pronounced kuái-sṳ́k-miêng.') where hanzi = '快熟麵' and notes like '%Pronounced sṳ́k-miêng.%';
update public.entries set romanization = 'gèng-dēng', headword = case when headword = 'gèng' then 'gèng-dēng' else headword end where hanzi = '懸頂' and romanization = 'gèng';
update public.entries set romanization = 'nguāi gáuk-nè̤ng', headword = case when headword = 'nguāi gáuk' then 'nguāi gáuk-nè̤ng' else headword end where hanzi = '我各儂' and romanization = 'nguāi gáuk';
update public.entries set notes = replace(notes, 'Pronounced gó̤k-nè̤ng.', 'Pronounced nguāi gó̤k-nè̤ng.') where hanzi = '我各儂' and notes like '%Pronounced gó̤k-nè̤ng.%';
update public.entries set romanization = 'pák-liáng-siáng', headword = case when headword = 'pák-liáng' then 'pák-liáng-siáng' else headword end where hanzi = '拍亮線' and romanization = 'pák-liáng';
update public.entries set notes = replace(notes, 'Pronounced liāng-siáng.', 'Pronounced pák-liāng-siáng.') where hanzi = '拍亮線' and notes like '%Pronounced liāng-siáng.%';
update public.entries set romanization = 'sáu-chiū-sĭng', headword = case when headword = 'sáu' then 'sáu-chiū-sĭng' else headword end where hanzi = '掃帚星' and romanization = 'sáu';
update public.entries set romanization = 'sáu-chiū', headword = case when headword = 'sáu' then 'sáu-chiū' else headword end where hanzi = '掃帚' and romanization = 'sáu';
update public.entries set romanization = 'ciēng-gák-huă', headword = case when headword = 'ciēng-gák' then 'ciēng-gák-huă' else headword end where hanzi = '掌甲花' and romanization = 'ciēng-gák';
update public.entries set notes = replace(notes, 'Pronounced gáh-*huă.', 'Pronounced ciēng-gáh-huă.') where hanzi = '掌甲花' and notes like '%Pronounced gáh-*huă.%';
update public.entries set romanization = 'sìng-ìng-giêu', headword = case when headword = 'sìng' then 'sìng-ìng-giêu' else headword end where hanzi = '新人轎' and romanization = 'sìng';
update public.entries set romanization = 'sṳ̀ng-mò̤-chiĕu', headword = case when headword = 'sṳ̀ng' then 'sṳ̀ng-mò̤-chiĕu' else headword end where hanzi = '松毛鬚' and romanization = 'sṳ̀ng';
update public.entries set romanization = 'ciēng-tàu-chiŏh', headword = case when headword = 'ciēng-tàu' then 'ciēng-tàu-chiŏh' else headword end where hanzi = '枕頭席' and romanization = 'ciēng-tàu';
update public.entries set notes = replace(notes, 'Pronounced tău-*chiŏh.', 'Pronounced ciēng-tău-chiŏh.') where hanzi = '枕頭席' and notes like '%Pronounced tău-*chiŏh.%';
update public.entries set romanization = 'sṳ̀ng-mò̤-cĕng', headword = case when headword = 'sṳ̀ng' then 'sṳ̀ng-mò̤-cĕng' else headword end where hanzi = '松毛針' and romanization = 'sṳ̀ng';
update public.entries set romanization = 'ciēng-tàu-sĭng', headword = case when headword = 'ciēng-tàu' then 'ciēng-tàu-sĭng' else headword end where hanzi = '枕頭心' and romanization = 'ciēng-tàu';
update public.entries set notes = replace(notes, 'Pronounced tău-sĭng.', 'Pronounced ciēng-tău-sĭng.') where hanzi = '枕頭心' and notes like '%Pronounced tău-sĭng.%';
update public.entries set romanization = 'léng-dĕng', headword = case when headword = 'léng' then 'léng-dĕng' else headword end where hanzi = '楞蟶' and romanization = 'léng';
update public.entries set notes = replace(notes, 'Pronounced láing-*dĕng.', 'Pronounced láing-dĕng.') where hanzi = '楞蟶' and notes like '%Pronounced láing-*dĕng.%';
update public.entries set romanization = 'nṳ̄ gáuk-nè̤ng', headword = case when headword = 'nṳ̄ gáuk' then 'nṳ̄ gáuk-nè̤ng' else headword end where hanzi = '汝各儂' and romanization = 'nṳ̄ gáuk';
update public.entries set notes = replace(notes, 'Pronounced gó̤k-nè̤ng.', 'Pronounced nṳ̄ gó̤k-nè̤ng.') where hanzi = '汝各儂' and notes like '%Pronounced gó̤k-nè̤ng.%';
update public.entries set romanization = 'ók-dāu', headword = case when headword = 'ók' then 'ók-dāu' else headword end where hanzi = '熨斗' and romanization = 'ók';
update public.entries set romanization = 'kēng-siéu', headword = case when headword = 'kēng' then 'kēng-siéu' else headword end where hanzi = '犬宿' and romanization = 'kēng';
update public.entries set notes = replace(notes, 'Pronounced kèng-*siéu.', 'Pronounced kèng-siéu.') where hanzi = '犬宿' and notes like '%Pronounced kèng-*siéu.%';
update public.entries set romanization = 'kēng-giāng-giāng', headword = case when headword = 'kēng-giāng' then 'kēng-giāng-giāng' else headword end where hanzi = '犬囝囝' and romanization = 'kēng-giāng';
update public.entries set notes = replace(notes, 'Pronounced iāng*-giāng.', 'Pronounced kēng-iāng-giāng.') where hanzi = '犬囝囝' and notes like '%Pronounced iāng*-giāng.%';
update public.entries set romanization = 'buòng-ngṳ̀', headword = case when headword = 'buòng' then 'buòng-ngṳ̀' else headword end where hanzi = '盆魚' and romanization = 'buòng';
update public.entries set romanization = 'mĕ̤k-sāi', headword = case when headword = 'mĕ̤k' then 'mĕ̤k-sāi' else headword end where hanzi = '目屎' and romanization = 'mĕ̤k';
update public.entries set romanization = 'áung-sṳ̀ng-báh-chéu', headword = case when headword = 'áung' then 'áung-sṳ̀ng-báh-chéu' else headword end where hanzi = '䁐松柏樹' and romanization = 'áung';
update public.entries set notes = replace(notes, 'Pronounced āung-*sṳ̀ng-báh-chéu.', 'Pronounced āung-sṳ̀ng-báh-chéu.') where hanzi = '䁐松柏樹' and notes like '%Pronounced āung-*sṳ̀ng-báh-chéu.%';
update public.entries set romanization = 'diăh-mī', headword = case when headword = 'diăh' then 'diăh-mī' else headword end where hanzi = '糴米' and romanization = 'diăh';
update public.entries set romanization = 'è̤ng-gŭng', headword = case when headword = 'è̤ng' then 'è̤ng-gŭng' else headword end where hanzi = '紅蚣' and romanization = 'è̤ng';
update public.entries set romanization = 'lâu-gŭng', headword = case when headword = 'lâu' then 'lâu-gŭng' else headword end where hanzi = '老公' and romanization = 'lâu';
update public.entries set romanization = 'lō̤-sŏ̤h-nĭk', headword = case when headword = 'lō̤-sŏ̤h' then 'lō̤-sŏ̤h-nĭk' else headword end where hanzi = '老昨日' and romanization = 'lō̤-sŏ̤h';
update public.entries set notes = replace(notes, 'Pronounced só̤h-nĭk.', 'Pronounced lō̤-só̤h-nĭk.') where hanzi = '老昨日' and notes like '%Pronounced só̤h-nĭk.%';
update public.entries set romanization = 'lō̤-sŏ̤h-nièng', headword = case when headword = 'lō̤' then 'lō̤-sŏ̤h-nièng' else headword end where hanzi = '老昨年' and romanization = 'lō̤';
update public.entries set romanization = 'hù-ciĕu-biāng', headword = case when headword = 'hù-ciĕu' then 'hù-ciĕu-biāng' else headword end where hanzi = '胡椒餅' and romanization = 'hù-ciĕu';
update public.entries set notes = replace(notes, 'Pronounced siĕu-biāng.', 'Pronounced hù-siĕu-biāng.') where hanzi = '胡椒餅' and notes like '%Pronounced siĕu-biāng.%';
update public.entries set romanization = 'cê̤ṳ-lài-huōi', headword = case when headword = 'cê̤ṳ-lài' then 'cê̤ṳ-lài-huōi' else headword end where hanzi = '自來火' and romanization = 'cê̤ṳ-lài';
update public.entries set notes = replace(notes, 'Pronounced làu-huōi.', 'Pronounced cê̤ṳ-làu-huōi.') where hanzi = '自來火' and notes like '%Pronounced làu-huōi.%';
update public.entries set romanization = 'mĕ̤k-lê-huă', headword = case when headword = 'mĕ̤k' then 'mĕ̤k-lê-huă' else headword end where hanzi = '茉莉花' and romanization = 'mĕ̤k';
update public.entries set romanization = 'mĕ̤k-lê', headword = case when headword = 'mĕ̤k' then 'mĕ̤k-lê' else headword end where hanzi = '茉莉' and romanization = 'mĕ̤k';
update public.entries set romanization = 'mĕ̤k-lê-huă-dà', headword = case when headword = 'mĕ̤k' then 'mĕ̤k-lê-huă-dà' else headword end where hanzi = '茉莉花茶' and romanization = 'mĕ̤k';
update public.entries set notes = replace(notes, 'Pronounced maĕ̤h-lê-*huă-dà.', 'Pronounced maĕ̤h-lê-huă-dà.') where hanzi = '茉莉花茶' and notes like '%Pronounced maĕ̤h-lê-*huă-dà.%';
update public.entries set romanization = 'niŏh-uâi', headword = case when headword = 'niŏh' then 'niŏh-uâi' else headword end where hanzi = '若夥' and romanization = 'niŏh';
update public.entries set romanization = 'lòi-sĭ-gā', headword = case when headword = 'lòi-sĭ' then 'lòi-sĭ-gā' else headword end where hanzi = '螺絲絞' and romanization = 'lòi-sĭ';
update public.entries set notes = replace(notes, 'Pronounced bĭ-*gā.', 'Pronounced lòi-bĭ-gā.') where hanzi = '螺絲絞' and notes like '%Pronounced bĭ-*gā.%';
update public.entries set romanization = 'dâu-hô', headword = case when headword = 'dâu' then 'dâu-hô' else headword end where hanzi = '豆腐' and romanization = 'dâu';
update public.entries set romanization = 'siê-iù', headword = case when headword = 'siê' then 'siê-iù' else headword end where hanzi = '豉油' and romanization = 'siê';
update public.entries set romanization = 'dâu-hô-ciŏng', headword = case when headword = 'dâu' then 'dâu-hô-ciŏng' else headword end where hanzi = '豆腐漿' and romanization = 'dâu';
update public.entries set notes = replace(notes, 'Pronounced dâ-hô-*ciŏng.', 'Pronounced dâ-hô-ciŏng.') where hanzi = '豆腐漿' and notes like '%Pronounced dâ-hô-*ciŏng.%';
update public.entries set romanization = 'mà-giāng', headword = case when headword = 'mà' then 'mà-giāng' else headword end where hanzi = '貓囝' and romanization = 'mà';
update public.entries set romanization = 'sĭng-sê̤ṳng', headword = case when headword = 'sĭng' then 'sĭng-sê̤ṳng' else headword end where hanzi = '身頌' and romanization = 'sĭng';
update public.entries set notes = replace(notes, 'Pronounced sīng-*sê̤ṳng.', 'Pronounced sīng-sê̤ṳng.') where hanzi = '身頌' and notes like '%Pronounced sīng-*sê̤ṳng.%';
update public.entries set romanization = 'dô̤-dâi', headword = case when headword = 'dô̤' then 'dô̤-dâi' else headword end where hanzi = '道士' and romanization = 'dô̤';
update public.entries set romanization = 'Ngià-uòng', headword = case when headword = 'Ngià' then 'Ngià-uòng' else headword end where hanzi = '閻王' and romanization = 'Ngià';
update public.entries set romanization = 'ciáh-ciáh', headword = case when headword = 'ciáh' then 'ciáh-ciáh' else headword end where hanzi = '隻隻' and romanization = 'ciáh';
update public.entries set notes = replace(notes, 'Pronounced ciéh\-ciáh.', 'Pronounced ciéh-ciáh.') where hanzi = '隻隻' and notes like '%Pronounced ciéh\-ciáh.%';
update public.entries set romanization = 'giĕ-găi', headword = case when headword = 'giĕ' then 'giĕ-găi' else headword end where hanzi = '雞胲' and romanization = 'giĕ';
update public.entries set notes = replace(notes, 'Pronounced giē-*găi.', 'Pronounced giē-găi.') where hanzi = '雞胲' and notes like '%Pronounced giē-*găi.%';
update public.entries set romanization = 'sĕ̤ng-kiê-nè̤ng', headword = case when headword = 'sĕ̤ng-kiê' then 'sĕ̤ng-kiê-nè̤ng' else headword end where hanzi = '雙徛人' and romanization = 'sĕ̤ng-kiê';
update public.entries set notes = replace(notes, 'Pronounced kiâ-nè̤ng.', 'Pronounced sĕ̤ng-kiâ-nè̤ng.') where hanzi = '雙徛人' and notes like '%Pronounced kiâ-nè̤ng.%';
update public.entries set romanization = 'ngiăh-tàu', headword = case when headword = 'ngiăh' then 'ngiăh-tàu' else headword end where hanzi = '額頭' and romanization = 'ngiăh';
update public.entries set romanization = 'tàu-sĕng', headword = case when headword = 'tàu' then 'tàu-sĕng' else headword end where hanzi = '頭先' and romanization = 'tàu';
update public.entries set romanization = 'siăh-buông', headword = case when headword = 'siăh' then 'siăh-buông' else headword end where hanzi = '食飯' and romanization = 'siăh';
update public.entries set notes = replace(notes, 'Pronounced siĕh-*buông.', 'Pronounced siĕh-buông.') where hanzi = '食飯' and notes like '%Pronounced siĕh-*buông.%';
update public.entries set romanization = 'siăh-iŏh', headword = case when headword = 'siăh' then 'siăh-iŏh' else headword end where hanzi = '食藥' and romanization = 'siăh';
update public.entries set romanization = 'siăh-cā', headword = case when headword = 'siăh' then 'siăh-cā' else headword end where hanzi = '食早' and romanization = 'siăh';
update public.entries set notes = replace(notes, 'Pronounced siĕh-*cā.', 'Pronounced siĕh-cā.') where hanzi = '食早' and notes like '%Pronounced siĕh-*cā.%';
update public.entries set romanization = 'siăh-dáu', headword = case when headword = 'siăh' then 'siăh-dáu' else headword end where hanzi = '食晝' and romanization = 'siăh';
update public.entries set notes = replace(notes, 'Pronounced siĕh-*dáu.', 'Pronounced siĕh-dáu.') where hanzi = '食晝' and notes like '%Pronounced siĕh-*dáu.%';
update public.entries set romanization = 'siăh-màng', headword = case when headword = 'siăh' then 'siăh-màng' else headword end where hanzi = '食暝' and romanization = 'siăh';
update public.entries set romanization = 'siăh lō̤ muôi', headword = case when headword = 'siăh' then 'siăh lō̤ muôi' else headword end where hanzi = '食𡅏未' and romanization = 'siăh';
update public.entries set romanization = 'siăh-chái', headword = case when headword = 'siăh' then 'siăh-chái' else headword end where hanzi = '食菜' and romanization = 'siăh';
update public.entries set notes = replace(notes, 'Pronounced siĕh-*chái.', 'Pronounced siĕh-chái.') where hanzi = '食菜' and notes like '%Pronounced siĕh-*chái.%';
update public.entries set romanization = 'siăh-giĕ', headword = case when headword = 'siăh' then 'siăh-giĕ' else headword end where hanzi = '食雞' and romanization = 'siăh';
update public.entries set notes = replace(notes, 'Pronounced siĕh-*giĕ.', 'Pronounced siĕh-giĕ.') where hanzi = '食雞' and notes like '%Pronounced siĕh-*giĕ.%';
update public.entries set romanization = 'siăh bā muôi', headword = case when headword = 'siăh' then 'siăh bā muôi' else headword end where hanzi = '食飽未' and romanization = 'siăh';
update public.entries set romanization = 'măh-ngà', headword = case when headword = 'măh' then 'măh-ngà' else headword end where hanzi = '麥芽' and romanization = 'măh';
update public.entries set romanization = 'liòng-sùng', headword = case when headword = 'liòng' then 'liòng-sùng' else headword end where hanzi = '龍船' and romanization = 'liòng';
-- 1b. markers left in a 'Pronounced' note
-- 2. glosses
update public.senses s set definition_en = 'short for 姨太太' from public.entries e where s.entry_id = e.id and e.hanzi = '姨太' and s.definition_en = 'short for for 姨太太';
update public.senses s set definition_en = 'short and small; undersized' from public.entries e where s.entry_id = e.id and e.hanzi = '矮嫩' and s.definition_en = 'short for and small; undersized';
update public.senses s set definition_en = 'short for 貓王鳥' from public.entries e where s.entry_id = e.id and e.hanzi = '貓王' and s.definition_en = 'short for for 貓王鳥';
update public.senses s set definition_en = 'short for 大雁鵝' from public.entries e where s.entry_id = e.id and e.hanzi = '雁鵝' and s.definition_en = 'short for for 大雁鵝';
update public.senses s set definition_en = 'short for 鼎邊糊' from public.entries e where s.entry_id = e.id and e.hanzi = '鼎邊' and s.definition_en = 'short for for 鼎邊糊';
-- 3. senses from other Chinese varieties
delete from public.senses s using public.entries e where s.entry_id = e.id and e.hanzi = '光棍' and s.definition_en = '(Sichuan) member of Gelaohui';
delete from public.senses s using public.entries e where s.entry_id = e.id and e.hanzi = '卵包' and s.definition_en = '(Sichuan, vulgar) scrotum';
delete from public.senses s using public.entries e where s.entry_id = e.id and e.hanzi = '塕塵' and s.definition_en = '(Dongshi, Putian) dust';
delete from public.senses s using public.entries e where s.entry_id = e.id and e.hanzi = '姆姆' and s.definition_en = '(Sichuan) middle-aged woman';
delete from public.senses s using public.entries e where s.entry_id = e.id and e.hanzi = '姪新婦' and s.definition_en = '(Pingxiang, Danyang) nephew''s wife brother''s son''s wife';
delete from public.senses s using public.entries e where s.entry_id = e.id and e.hanzi = '斧頭' and s.definition_en = '(Sichuan) one of the suits of Sichuan playing cards';
delete from public.senses s using public.entries e where s.entry_id = e.id and e.hanzi = '歡喜' and s.definition_en = '(including, Sichuanese) to like; to be fond of';
delete from public.senses s using public.entries e where s.entry_id = e.id and e.hanzi = '玻璃' and s.definition_en = '(Sichuanese, humorous) plain boiled water';
delete from public.senses s using public.entries e where s.entry_id = e.id and e.hanzi = '白話字' and s.definition_en = '(Putian) Báⁿ-uā-ci̍ a Latin alphabet-based orthography for Puxian Min; BUC';
delete from public.senses s using public.entries e where s.entry_id = e.id and e.hanzi = '穿心爿' and s.definition_en = '(Putian) 忄';
delete from public.senses s using public.entries e where s.entry_id = e.id and e.hanzi = '算盤子' and s.definition_en = '(Putian) finger ring with dotted patterns';
delete from public.senses s using public.entries e where s.entry_id = e.id and e.hanzi = '籃籃' and s.definition_en = '(Sichuan) basket';
delete from public.senses s using public.entries e where s.entry_id = e.id and e.hanzi = '細婆' and s.definition_en = '(Putian) concubine';
delete from public.senses s using public.entries e where s.entry_id = e.id and e.hanzi = '羊眩' and s.definition_en = '(Putian) dizziness';
delete from public.senses s using public.entries e where s.entry_id = e.id and e.hanzi = '陰陽' and s.definition_en = '(Sichuan) fengshui master; geomancer';
delete from public.senses s using public.entries e where s.entry_id = e.id and e.hanzi = '雨濛' and s.definition_en = '(Putian) drizzle';
delete from public.senses s using public.entries e where s.entry_id = e.id and e.hanzi = '電視' and s.definition_en = '(Putian, mahjong) white dragon';
delete from public.senses s using public.entries e where s.entry_id = e.id and e.hanzi = '飛機' and s.definition_en = '(Sichuan) hoodlum; hooligan; street urchin';
delete from public.senses s using public.entries e where s.entry_id = e.id and e.hanzi = '鴨母' and s.definition_en = '(Sichuanese) female duck';
delete from public.senses s using public.entries e where s.entry_id = e.id and e.hanzi = '鼎巴' and s.definition_en = '(Putian) rice crust; crust of cooked rice';
update public.entries e set status = 'pending', review_notes = 'Its only meaning came from another Chinese variety and was removed; needs a Fuzhou meaning before it can be published.'
  where e.status = 'approved' and not exists (select 1 from public.senses s where s.entry_id = e.id);
commit;
