#!/usr/bin/env python3
"""Generates supabase/content_fixes.sql from scripts/wiktionary-words.csv and
patches the CSV in place. One-off for the 2026-09-09 review; kept so the
reasoning is reproducible. Run from the repo root."""
import csv, os, re

CSV = "scripts/wiktionary-words.csv"
OUT = "supabase/content_fixes.sql"

rows = list(csv.DictReader(open(CSV, encoding="utf-8")))


def q(s):
    return "'" + s.replace("'", "''") + "'"


def strip_markers(s):
    return re.sub(r"[*!\\]", "", s)


def cjk_count(h):
    return len([c for c in h if ("一" <= c <= "鿿") or ("㐀" <= c <= "䶿") or (0x20000 <= ord(c) <= 0x323AF)])


sql = ["""-- ---------------------------------------------------------------------------
--  Content fixes after the 2026-09-09 site review (supabase/content_fixes.sql)
--
--  1. Wiktionary imports whose romanization was cut short. Wiktionary writes
--     a syllable's context pronunciation as "cit>actual" inside the word
--     (仂囝 nék>ník-giāng); the harvest split the whole word at ">" and kept
--     only what came before it. Rebuilt here from the two halves, and the
--     "Pronounced …" note gets the markers (* ! \\) stripped as well.
--  2. "short for for" → "short for"; 矮嫩 "short for and small" → "short and small".
--  3. Senses labelled for another Chinese variety (Sichuan, Putian, Danyang…)
--     are removed — the character has a Fuzhou reading but that meaning is
--     not attested for Fuzhou. A word left with no meaning goes back to
--     pending with a review note.
--  Every statement is keyed by hanzi + the exact old text, so re-running is
--  a no-op. Generated by scripts/content-fixes.py.
-- ---------------------------------------------------------------------------
begin;
"""]

# --- 1. romanization ---
seen = set()
fixes = []
unresolved = []
for r in rows:
    h = r["hanzi"]
    rom = r["romanization"].strip()
    if (h, rom) in seen:
        continue
    seen.add((h, rom))
    hc = cjk_count(h)
    rs = re.split(r"[-\s]+", rom) if rom else []
    if hc >= 2 and rs and len(rs) < hc:
        m = re.search(r"Pronounced ([^.]+)\.", r["notes"])
        if not m:
            unresolved.append((h, rom, "no pronounced note"))
            continue
        act = m.group(1).strip()
        asyl = re.split(r"[-\s]+", act)
        seps = re.findall(r"[-\s]+", act)
        rseps = re.findall(r"[-\s]+", rom)
        cit = rs + asyl[1:]        # a1 replaces bk
        pron = rs[:-1] + asyl
        if len(cit) != hc:
            unresolved.append((h, rom, act))
            continue

        def join(sy):
            allseps = rseps + seps
            out = sy[0]
            for i, s in enumerate(sy[1:]):
                out += (allseps[i] if i < len(allseps) else "-") + s
            return out

        fixes.append((h, rom, strip_markers(join(cit)), act, strip_markers(join(pron))))

sql.append("-- 1. romanization rebuilt (%d words)" % len(fixes))
for h, old, new, act, pron in fixes:
    sql.append(
        f"update public.entries set romanization = {q(new)}, headword = case when headword = {q(old)} then {q(new)} else headword end where hanzi = {q(h)} and romanization = {q(old)};"
    )
    if pron != act:
        sql.append(
            f"update public.entries set notes = replace(notes, {q('Pronounced ' + act + '.')}, {q('Pronounced ' + pron + '.')}) where hanzi = {q(h)} and notes like {q('%Pronounced ' + act + '.%')};"
        )

fixed_h = {f[0] for f in fixes}
sql.append("-- 1b. markers left in a 'Pronounced' note")
seenn = set()
for r in rows:
    m = re.search(r"Pronounced ([^.]+)\.", r["notes"])
    if m and re.search(r"[*!\\]", m.group(1)) and r["hanzi"] not in fixed_h and r["hanzi"] not in seenn:
        seenn.add(r["hanzi"])
        sql.append(
            f"update public.entries set notes = replace(notes, {q('Pronounced ' + m.group(1) + '.')}, {q('Pronounced ' + strip_markers(m.group(1)) + '.')}) where hanzi = {q(r['hanzi'])} and notes like {q('%Pronounced ' + m.group(1) + '.%')};"
        )

# --- 2. glosses ---
sql.append("-- 2. glosses")
gl = []
for r in rows:
    d = r["definition_en"]
    if "short for for" in d:
        gl.append((r["hanzi"], d, d.replace("short for for", "short for")))
    elif d.startswith("short for and small"):
        gl.append((r["hanzi"], d, d.replace("short for and small", "short and small")))
for h, old, new in gl:
    sql.append(
        f"update public.senses s set definition_en = {q(new)} from public.entries e where s.entry_id = e.id and e.hanzi = {q(h)} and s.definition_en = {q(old)};"
    )

# --- 3. dialect senses ---
sql.append("-- 3. senses from other Chinese varieties")
dl = []
for r in rows:
    d = r["definition_en"]
    if re.search(r"\((?:[^)]*,\s*)?(?:Danyang|Putian|Sichuan|Sichuanese|Dongshi|Pingxiang)\b[^)]*\)", d):
        dl.append((r["hanzi"], d))
for h, d in dl:
    sql.append(
        f"delete from public.senses s using public.entries e where s.entry_id = e.id and e.hanzi = {q(h)} and s.definition_en = {q(d)};"
    )
sql.append(
    """update public.entries e set status = 'pending', review_notes = 'Its only meaning came from another Chinese variety and was removed; needs a Fuzhou meaning before it can be published.'
  where e.status = 'approved' and not exists (select 1 from public.senses s where s.entry_id = e.id);
commit;"""
)
open(OUT, "w", encoding="utf-8").write("\n".join(sql) + "\n")

# --- the same fixes in the CSV ---
fixmap = {(h, old): (new, act, pron) for h, old, new, act, pron in fixes}
glmap = {(h, old): new for h, old, new in gl}
dlset = set(dl)
out = []
dropped = 0
for r in rows:
    key = (r["hanzi"], r["romanization"].strip())
    if key in fixmap:
        new, act, pron = fixmap[key]
        r["romanization"] = new
        r["notes"] = r["notes"].replace("Pronounced " + act + ".", "Pronounced " + pron + ".")
    m = re.search(r"Pronounced ([^.]+)\.", r["notes"])
    if m and re.search(r"[*!\\]", m.group(1)):
        r["notes"] = r["notes"].replace("Pronounced " + m.group(1) + ".", "Pronounced " + strip_markers(m.group(1)) + ".")
    k2 = (r["hanzi"], r["definition_en"])
    if k2 in glmap:
        r["definition_en"] = glmap[k2]
    if k2 in dlset:
        dropped += 1
        continue
    out.append(r)
w = csv.DictWriter(open(CSV + ".new", "w", newline="", encoding="utf-8"), fieldnames=rows[0].keys())
w.writeheader()
for r in out:
    w.writerow(r)
os.replace(CSV + ".new", CSV)

print(len(fixes), "romanizations;", len(gl), "glosses;", len(dl), "senses removed; csv", len(rows), "->", len(out))
print("unresolved:", unresolved)
